version: 2.1
jobs:
  build:
    docker:
      - image: circleci/node:12.22.2
      - image: circleci/node:12.22.2
    steps:
      - checkout
      - run:
          name: install-dependent
          command: npm install
      - run:
          name: build
          command: npm run build