version: 2.1
jobs:
  build:
    docker:
      - image: circleci/node:14.15.5
      - image: circleci/node:14.15.5
    steps:
      - checkout
      - run:
          name: install-dependent
          command: npm install
      - run:
          name: build
          command: npm run build